# .github/workflows/deploy.yml

name: Deploy Quartz
on:
  push:
    branches:
      - main # ou a branch que você usa como principal

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessário para o plugin de histórico do git

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          # Lê a versão do seu arquivo .node-version
          node-version-file: ".node-version"
          # Configura o cache para pnpm, para builds mais rápidos
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build Quartz
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4